# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: pretty

# Setup
title: and they're robin'
tagline: 'design, programming, and life'
description: 'Talking about programming, game design, creativity, and life in general.'
baseurl: ''
paginate: 8
github_username: andey-robins

# About/contact
author:
  name: Andey Robins
  email: jtuttle5@uwyo.edu

# Custom vars
version: 1.0.0

# Gems
gems: [jekyll-paginate]
